lib/app/app.dart
lib/app/providers/bloc_providers.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/bloc/auth_event.dart
lib/screens/welcome/bloc/auth_state.dart
lib/screens/welcome/bloc/bloc.dart
lib/screens/welcome/welcome.dart
lib/widgets/end_drawer/end_drawer.dart

- Creates a bloc for handling authentication 
- Refactor common methods to class 
- User information will be extracted from shared prefs in a follow up PR

Initial set up of auth bloc 

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Update gradle version

---

lib/screens/expression_open/expressions/audio_open.dart

Moved function declaration out of the build method

Move function out of build 

---

lib/app/app.dart
lib/app/material_app_with_theme.dart
lib/app/themes_provider.dart
lib/hive_keys.dart
lib/screens/welcome/bloc/auth_bloc.dart

Refactor MaterialAppWithTheme

---

lib/screens/collective/bloc/collective_bloc.dart

Don't access expression results in log when no expressions

---

lib/backend/repositories/auth_repo.dart
lib/backend/services/auth_service.dart
lib/backend/user_data_provider.dart
lib/models/group_model.dart
lib/widgets/end_drawer/end_drawer.dart

- fix #653
The main issue was here:
```dart
await box.put(HiveKeys.kUserData, jsonEncode(response.body));	
return UserData.fromMap(JuntoHttp.handleResponse(response));	
```
which should be :
```dart
final userData = JuntoHttp.handleResponse(response);
final user = UserData.fromMap(userData);
await box.put(HiveKeys.kUserData, jsonEncode(user));
return user;
```

Fix signup issue 

---

lib/backend/backend.dart
lib/backend/repositories/auth_repo.dart
lib/backend/services/auth_service.dart
lib/backend/services/expression_provider.dart
lib/backend/user_data_provider.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/bloc/auth_event.dart
lib/screens/welcome/sign_up_photos.dart
lib/screens/welcome/welcome.dart

So I removed uploading image from welcome.dart but the signup process after switching to bloc must be rewritten from the grounds up.
Right now we have many issues there. I had to add a completer to wait for the signup process but this is so wrong. 
Also because we switch the screen after sign up, not after accepting terms, we don't navigate the user to the terms page.
- fix #669
- fix #653 
- fix #670

Allow to add images during sign up

---

lib/backend/user_data_provider.dart
lib/screens/collective/perspectives/collective_populated_list.dart
lib/screens/expression_open/expressions/photo_open.dart
lib/widgets/custom_feeds/custom_listview.dart
lib/widgets/custom_feeds/group_expressions.dart
lib/widgets/custom_feeds/single_listview.dart
lib/widgets/custom_feeds/user_expressions.dart
lib/widgets/image_wrapper.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/photo.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/audio.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/photo.dart
pubspec.yaml

Reverts juntofoundation/junto-mobile#683

Revert "Fixes various performance issues"

---

lib/app/material_app_with_theme.dart
lib/backend/repositories/auth_repo.dart
lib/generated/intl/messages_de.dart
lib/generated/intl/messages_en.dart
lib/generated/intl/messages_pl.dart
lib/generated/intl/messages_pt.dart
lib/generated/l10n.dart
lib/l10n/intl_de.arb
lib/l10n/intl_en.arb
lib/l10n/intl_pl.arb
lib/l10n/intl_pt.arb
lib/screens/welcome/sign_up_photos.dart
lib/screens/welcome/welcome.dart
lib/screens/welcome/widgets/sign_up_profile_picture.dart

Rearranged a bit how profile picture is selected in welcome.dart

Sign up image selection refactor

---

lib/backend/repositories/notification_repo.dart
lib/backend/services.dart
lib/backend/services/hive_service.dart
lib/models/group_model.dart
lib/models/junto_notification.dart
lib/models/junto_notification.g.dart
lib/screens/create/create_templates/longform.dart
lib/screens/groups/bloc/group_bloc.dart
lib/screens/notifications/notification_types/connection_request_notification.dart
lib/screens/notifications/notification_types/pack_request_notification.dart
lib/screens/notifications/notifications_handler.dart
lib/screens/notifications/utils/text_span_nav.dart
lib/screens/notifications/utils/username_text_span.dart
lib/screens/notifications/widgets/connection_request_response.dart
lib/screens/notifications/widgets/notification_tile.dart
lib/screens/notifications/widgets/pack_request_response.dart
lib/screens/notifications/widgets/user_navigation_wrapper.dart
lib/screens/notifications/widgets/user_profile_picture.dart
lib/screens/packs/pack_requests.dart
lib/widgets/end_drawer/end_drawer_relationships/pending/pending_pack_members.dart
lib/widgets/previews/pack_preview/pack_request.dart

- Fix #679 
Waiting on API to return "creator" instead of "user" in group response data to Fix #680

Fix notifications [WIP]

---

lib/app/main_app.dart
lib/app/material_app_with_theme.dart
lib/screens/welcome/sign_up_themes.dart
lib/screens/welcome/welcome.dart
lib/utils/bloc_delegate.dart
lib/widgets/end_drawer/end_drawer.dart
pubspec.yaml

The problem was with the fact that during logout we navigated to Welcome. It's not necessary.
fix #691

Fix sign up agreements

---

lib/backend/services/user_service.dart
lib/screens/member/member_action_items/connected_action_items.dart
lib/screens/member/member_action_items/no_relationship_action_items.dart
lib/screens/member/member_action_items/pack_action_items.dart
lib/screens/member/member_action_items/subscribed_action_items.dart
lib/screens/member/member_relationships.dart
lib/screens/packs/pack_open/pack_open_appbar.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/sign_up_agreement.dart
lib/screens/welcome/welcome.dart
lib/screens/welcome/widgets/junto_rules.dart
lib/screens/welcome/widgets/junto_terms.dart
lib/screens/welcome/widgets/sign_up_accept_button.dart
lib/widgets/appbar/collective_appbar.dart
lib/widgets/end_drawer/end_drawer_relationships/end_drawer_relationships.dart
lib/widgets/end_drawer/end_drawer_relationships/pack_members.dart
lib/widgets/end_drawer/end_drawer_relationships/pending/pending_pack_members.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart
lib/widgets/previews/pack_preview/pack_preview.dart

- Enable swipe back for two column photo preview
- Close #706 
- Refine Pack Appbar
- Temp fix for PackActionItems

Various ops

---

lib/app/material_app_with_theme.dart
lib/generated/intl/messages_de.dart
lib/generated/intl/messages_en.dart
lib/generated/intl/messages_pl.dart
lib/generated/intl/messages_pt.dart
lib/generated/l10n.dart
lib/l10n/intl_de.arb
lib/l10n/intl_en.arb
lib/l10n/intl_pl.arb
lib/l10n/intl_pt.arb
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/bloc/auth_state.dart
lib/screens/welcome/bloc/auth_state.freezed.dart
lib/screens/welcome/reset_password_confirm.dart
lib/screens/welcome/reset_password_request.dart
lib/screens/welcome/sign_in.dart
lib/screens/welcome/welcome.dart

Improve error handling during sing in and sign up

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/user_repo.dart
lib/backend/services.dart
lib/backend/services/user_service.dart
lib/screens/lotus/lotus.dart
lib/screens/packs/pack_open/pack_open_appbar.dart
lib/widgets/bottom_nav.dart
pubspec.yaml

- Closes #714 
- Cleans up imports

Fixed imports and packages

---

lib/backend/backend.dart
lib/backend/repositories/auth_repo.dart

Inconsistent theme 

---

lib/app/app.dart
lib/app/page_index_provider.dart
lib/backend/backend.dart
lib/screens/collective/collective.dart
lib/screens/packs/packs.dart
lib/widgets/background/background_theme.dart

Dynamically pass initial page to collective + packs page views

---

lib/backend/repositories/notification_repo.dart
lib/screens/comment_open/comment_open.dart
lib/screens/packs/pack_open/pack_actions_button.dart
lib/widgets/action_items/comment_action_items.dart
lib/widgets/end_drawer/end_drawer.dart
lib/widgets/end_drawer/junto_resources.dart
lib/widgets/previews/comment_preview.dart

- Closes #685 
- Minor code clean up

Resolve #685

---

lib/backend/mock/mock_auth.dart
lib/backend/repositories/auth_repo.dart
lib/backend/services.dart
lib/backend/services/auth_service.dart
lib/models/user_model.dart
lib/models/user_model.g.dart
lib/widgets/dialogs/delete_account_dialog.dart
lib/widgets/dialogs/single_action_dialog.dart
lib/widgets/end_drawer/end_drawer.dart
lib/widgets/end_drawer/junto_account.dart
lib/widgets/end_drawer/junto_account_appbar.dart

- Closes #421 
- Closes #729 
Hey @orestesgaolin - updated the UserProfile model in user_model.dart to accommodate emails. Noticed we have an automatically generated user_model.g.dart file as well. Is this also through freezed / and will I just need to call `flutter pub pub run build_runner build` ?

Delete user account 

---

lib/backend/repositories/app_repo.dart

Make two-column layout default

---

lib/screens/create/create_actions/create_actions.dart

Fixed Collective and Pack refresh.

Closes #733

---

lib/screens/collective/collective.dart
lib/screens/member/member_action_items/connected_action_items.dart
lib/screens/member/member_action_items/pack_action_items.dart
lib/screens/member/member_relationships.dart
lib/screens/packs/pack_open/pack_open_action_items.dart
lib/widgets/dialogs/confirm_dialog.dart
lib/widgets/drawer/junto_filter_drawer.dart
lib/widgets/end_drawer/end_drawer.dart

- Implement custom swipe drawer animation
- Fix CustomDialog across app and MemberRelationships action items

Clean up final

---

lib/screens/notifications/notification_navigation_observer.dart

Add extra null checks in navigation observer

---

lib/widgets/rich_text_editor/nodes/bullet_list.dart
lib/widgets/rich_text_editor/nodes/quote_node.dart
lib/widgets/rich_text_editor/nodes/text_node.dart
lib/widgets/rich_text_editor/nodes/types.dart
lib/widgets/rich_text_editor/rich_text_controller.dart
lib/widgets/rich_text_editor/rich_text_editor.dart

I extracted and tweaked the logic of RTE to separate controller.
I'm not attached to any of the names or conventions yet, so please consider this as a step towards a working prototype ;)

Extract some parts of RTE logic to the controller

---

lib/app/app.dart
lib/backend/backend.dart
lib/backend/repositories/app_repo.dart
lib/backend/repositories/auth_repo.dart
lib/backend/repositories/onboarding_repo.dart
lib/hive_keys.dart
lib/screens/collective/collective.dart
lib/screens/collective/collective_actions/perspectives_appbar.dart
lib/screens/create/create.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/expression_open/expressions/photo_open.dart
lib/screens/lotus/lotus.dart
lib/screens/packs/pack_open/pack_open.dart
lib/screens/packs/pack_open/pack_tabs.dart
lib/screens/packs/packs_list_appbar.dart
lib/widgets/appbar/collective_appbar.dart
lib/widgets/drawer/junto_filter_drawer.dart
lib/widgets/image_wrapper.dart

This PR touches on a few issues, the primary focus was on automatically showing the user tutorial when the user first signs up. In addition to this, the following issues also touched:
- Closes #727
- Closes #763
- Closes #769 (Bloc context not available)
- Closes #771

Automatically show user tutorial 

---

lib/backend/repositories/onboarding_repo.dart

Disable in app tutorial

---

lib/screens/create/create_actions/create_actions.dart

Fix share description

---

lib/backend/repositories/app_repo.dart
lib/backend/user_data_provider.dart
lib/screens/collective/perspectives/collective_populated_list.dart
lib/screens/create/create_actions/widgets/create_app_bar.dart
lib/screens/welcome/welcome.dart
lib/widgets/appbar/collective_appbar.dart
lib/widgets/custom_feeds/group_expressions.dart
lib/widgets/custom_feeds/user_expressions.dart
lib/widgets/dialogs/confirm_dialog.dart
lib/widgets/end_drawer/end_drawer.dart

This PR closes the following high priority issues raised by the team:
- Closes #793
- Closes #818
- Closes #764
- Added "route" method to welcome screen
- Fixed callback function in the confirmation dialog

Various high priority bugs

---

lib/widgets/end_drawer/end_drawer.dart

Fixed regression on the latest dev.

Fixed logout function

---

lib/screens/expression_open/expressions/photo_open.dart
lib/widgets/end_drawer/end_drawer.dart

Placeholder and image height and fit are now the same. 
- Closes #828

Resolve image and placeholder height

---

lib/backend/services/auth_cognito_service.dart
lib/screens/welcome/bloc/auth_bloc.dart

Handle wrong username and password correctly

---

lib/models/user_model.dart

related to #840
@Nash0x7E2 it adds createdAt property to UserProfile

Provide createdAt in UserProfile

---

.gitignore
lib/app/app.dart
lib/app/providers/bloc_providers.dart
lib/backend/backend.dart
lib/backend/repositories/onboarding_repo.dart
lib/hive_keys.dart
lib/models/auth_result.dart
lib/screens/collective/collective.dart
lib/screens/collective/perspectives/about_perspective.dart
lib/screens/collective/perspectives/collective_populated_list.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/create/create_actions/widgets/create_app_bar.dart
lib/screens/lotus/lotus.dart
lib/screens/packs/pack_open/pack_open_action_items.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/widgets/end_drawer/end_drawer.dart
lib/widgets/end_drawer/end_drawer_relationships/end_drawer_relationships.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart

This PR migrates changes made by #839 and #833 to the latest dev and cognito.
Associated issues from the previous PRs can be closed once this is merged. 
- Closes #838
- Closes #825
- Closes #814
- Closes #778

Migrate existing PRs

---

lib/screens/expression_open/expressions/photo_open.dart

Fix photo cropping

---

android/app/proguard-rules.pro

Fix proguard rules to keep AWS classes

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/auth_repo.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/auth_cognito_service.dart
lib/backend/services/user_service.dart
lib/backend/services_auth.dart
lib/backend/services_user.dart
lib/models/expression.dart
lib/models/user_model.dart
lib/widgets/dialogs/delete_account_dialog.dart

This PR adds the ability for users to remove their account. 
- Migrated delete account from cognito auth to user service 
- Updated references 
- Fixed minor lint rules and code clean up

Delete user account

---

lib/models/user_model.dart
lib/screens/packs/pack_open/pack_open_action_items.dart

- Fixes view pack member crash: Looks like `connectionPerspective` is nullable 
- Closes #836

Fix pack navigation crash

---

lib/app/themes_provider.dart
lib/backend/repositories/onboarding_repo.dart
lib/hive_keys.dart
lib/models/user_model.g.dart
lib/screens/groups/spheres/spheres_temp_appbar.dart
lib/widgets/end_drawer/junto_themes_page.dart

Fix theme vibration on launch

---

ios/Flutter/.last_build_id
lib/backend/repositories/auth_repo.dart
lib/screens/welcome/reset_password_confirm.dart
lib/screens/welcome/welcome.dart
pubspec.yaml

- Fixes password reset on iOS 
- Checks for null tokens 
- calls signout before logging in a user
- Related #840

Password Reset on iOS

---

lib/backend/repositories/onboarding_repo.dart
lib/hive_keys.dart
lib/models/user_model.g.dart
lib/screens/groups/spheres/spheres_temp_appbar.dart

show tutorial in groups

---

lib/screens/welcome/reset_password_confirm.dart
lib/screens/welcome/reset_password_request.dart

Fix loader bug

---

.gitignore
lib/backend/mock/mock_auth.dart
lib/backend/repositories/auth_repo.dart
lib/backend/services/auth_cognito_service.dart
lib/backend/services_auth.dart
lib/generated/intl/messages_de.dart
lib/generated/intl/messages_en.dart
lib/generated/intl/messages_pl.dart
lib/generated/intl/messages_pt.dart
lib/generated/l10n.dart
lib/l10n/intl_de.arb
lib/l10n/intl_en.arb
lib/l10n/intl_pl.arb
lib/l10n/intl_pt.arb
lib/models/auth_result.dart
lib/screens/welcome/reset_password_confirm.dart
lib/screens/welcome/reset_password_request.dart
lib/screens/welcome/sign_up_verify.dart
lib/screens/welcome/welcome.dart
lib/screens/welcome/widgets/resend_verification_code_button.dart
lib/widgets/buttons/call_to_action.dart
lib/widgets/dialogs/user_feedback.dart

This PR allows users to resend a confirmation code during the registration and forget password flows.
- Related #863 
- Close #859

Resend verification code

---

lib/backend/services/auth_cognito_service.dart
lib/screens/welcome/reset_password_request.dart
lib/screens/welcome/sign_in.dart
lib/screens/welcome/widgets/welcome_main.dart
lib/widgets/buttons/call_to_action.dart
lib/widgets/dialogs/user_feedback.dart

Fixes to password reset

---

lib/backend/services/auth_cognito_service.dart
lib/widgets/dialogs/user_feedback.dart

Fixes for password reset on iOS

---

lib/screens/create/create_actions/create_actions.dart
lib/screens/expression_open/expression_open_top.dart
lib/screens/welcome/reset_password_confirm.dart
lib/screens/welcome/sign_in.dart
lib/screens/welcome/sign_up_verify.dart
lib/screens/welcome/widgets/sign_up_accept_button.dart
lib/screens/welcome/widgets/welcome_main.dart
lib/widgets/action_items/expression_action_items.dart
lib/widgets/custom_feeds/custom_listview.dart
lib/widgets/custom_feeds/filter_column_row.dart
lib/widgets/custom_feeds/group_expressions.dart
lib/widgets/custom_feeds/single_listview.dart
lib/widgets/custom_feeds/user_expressions.dart
lib/widgets/end_drawer/junto_center.dart
lib/widgets/end_drawer/junto_center/junto_center_feedback.dart
lib/widgets/previews/expression_preview/expression_preview_bottom.dart

Complete v1 of community center

Finish community center

---

lib/screens/welcome/sign_up_photos.dart

Fix image selection

---

lib/backend/services/group_service.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/welcome/widgets/sign_up_accept_button.dart
lib/widgets/end_drawer/junto_center.dart
lib/widgets/end_drawer/junto_center/junto_center_appbar.dart
lib/widgets/end_drawer/junto_center/junto_center_updates.dart

Build updates section for community center

Community center updates

---

lib/backend/services/hive_service.dart
lib/screens/den/den_sliver_appbar.dart
lib/screens/den/edit_den/edit_den_button.dart
lib/screens/welcome/sign_in.dart
lib/widgets/custom_feeds/group_expressions.dart
lib/widgets/custom_feeds/user_expressions.dart

- This PR fixes the initialization crash thrown by Hive. Once we detect a hive error, all local boxes are cleared then the Box is reinitialized
- Fixes the edit den button not responding to touch events 
- Minor clean up of imports

Fixed Hive initialization crash 

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/auth_repo.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/user_service.dart
lib/backend/services_user.dart

Call the new endpoint to delete unverified account if such exists

---

lib/screens/comment_open/comment_open.dart
lib/screens/comment_open/comment_open_top.dart
lib/screens/expression_open/expression_open.dart
lib/screens/expression_open/expression_open_top.dart
lib/screens/notifications/widgets/notification_tile.dart
lib/widgets/action_items/comment_action_items.dart
lib/widgets/comments/comments_list.dart
lib/widgets/previews/comment_preview.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/shortform.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/shortform.dart

- added RepaintBoundary
- tested several times in various configs in profile mode on iP6s and it's much smoother
- don't pass user address or any other properties globally available through constructors

Improve feed performance

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/user_service.dart
lib/backend/services_user.dart
lib/widgets/bottom_nav.dart
lib/widgets/end_drawer/junto_invite.dart
lib/widgets/end_drawer/junto_invite_dialog.dart

Fix invite user error handling
Polish global search nav

Edge cases

---

lib/widgets/bottom_nav.dart

* Fixed Lotus menu in Den screen

Fixes lotus button in Den

---

lib/screens/collective/bloc/collective_bloc.dart
lib/screens/collective/perspectives/expression_feed.dart
pubspec.lock

Close #945

---

ios/Podfile
ios/Podfile.lock
lib/screens/create/create_actions/create_actions.dart
lib/screens/welcome/widgets/sign_up_accept_button.dart
lib/utils/bloc_delegate.dart
lib/widgets/custom_feeds/single_listview.dart
pubspec.lock
pubspec.yaml

- Updates Flutter bloc to v6 
- Update Podfile on IOS 
- Clean up imports

Update Flutter bloc and Podfile

---

lib/app/material_app_with_theme.dart
lib/screens/packs/pack_open/pack_open.dart
pubspec.lock
pubspec.yaml

- Checks for hive issue on first launch

Prod Bug Fixes 

---

lib/app/material_app_with_theme.dart
lib/backend/repositories/app_repo.dart
lib/backend/services/app_service.dart
lib/backend/services/user_service.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/bloc/auth_event.dart

- Refresh the user's auth state if the profile is null.

Refresh user's auth state

---

lib/app/material_app_with_theme.dart
lib/backend/repositories/app_repo.dart
lib/backend/services/app_service.dart
lib/backend/services/user_service.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/bloc/auth_event.dart

Reverts juntofoundation/junto-mobile#974

Revert "Refresh user's auth state"

---

lib/screens/den/den.dart
lib/screens/den/edit_den/edit_den.dart
lib/widgets/end_drawer/end_drawer.dart
lib/widgets/member_widgets/about_item.dart

- Remove double url prefix in den 
- Closes #969

Remove double url prefix in den

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/user_service.dart
lib/backend/services_user.dart
lib/widgets/end_drawer/junto_invite.dart
lib/widgets/end_drawer/junto_invite_dialog.dart
lib/widgets/end_drawer/junto_invite_notice.dart
lib/widgets/utils/date_parsing.dart

Refactor invites [WIP]

---

android/app/src/tst/AndroidManifest.xml
ios/Podfile
ios/Podfile.lock
ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
lib/backend/repositories/app_repo.dart
lib/backend/services/app_service.dart
lib/backend/services/auth_cognito_service.dart
pubspec.lock
pubspec.yaml

Resolve iOS sign-in issue. 
This occurred due to a platform/package error, please see:
- https://github.com/agnostech/flutter_amplify/pull/20
- https://github.com/agnostech/flutter_amplify/issues/19

Login issue on IOS

---

lib/app/material_app_with_theme.dart
lib/screens/expression_open/expressions/audio_open.dart
lib/screens/expression_open/expressions/longform_open.dart
lib/screens/expression_open/expressions/photo_open.dart
lib/screens/expression_open/expressions/shortform_open.dart
lib/widgets/previews/comment_preview/previews/dynamic.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/dynamic.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/shortform.dart

- Fixes cut off captions
- Adds check server version in app lifecycle state

Junto Alpha 0.2.3 (58)

---

lib/widgets/custom_feeds/filter_column_widget.dart
lib/widgets/custom_feeds/user_expressions.dart
lib/widgets/end_drawer/junto_center.dart
lib/widgets/end_drawer/junto_center/junto_center_appbar.dart
lib/widgets/end_drawer/junto_center/junto_center_feedback.dart
lib/widgets/end_drawer/junto_center/junto_center_support_notice.dart
lib/widgets/end_drawer/junto_center/junto_center_updates.dart

- Add support email notice at the top of each feed
- Swap updates and feedback order
- Code refactor + improvements

Community center improvements

---

lib/screens/create/create_templates/link.dart

@Nash0x7E2  I'll leave the title issue up to you

Patch linkform 

---

lib/screens/collective/perspectives/expression_feed.dart
lib/screens/packs/pack_open/pack_open.dart
lib/widgets/end_drawer/junto_center.dart

Fix floating appbar

---

lib/backend/mock/mock_user.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/user_service.dart
lib/backend/services_user.dart
lib/widgets/end_drawer/junto_invite_dialog.dart

- Set return data of invite user to null instead of status code
- Patch post-invite dialog navigation
~ waiting on Josh to look into timestamp of last invite sent

Clean up invite user functionality [WIP]

---

lib/filters/bloc/channel_filtering_bloc.dart
lib/screens/create/create_actions/channel_search_modal.dart
lib/widgets/drawer/widgets/filter_drawer_text_field.dart

Enable popular channels in search throughout app

---

lib/backend/repositories/user_repo.dart
lib/backend/user_data_provider.dart
lib/screens/welcome/bloc/auth_bloc.dart

- Capture error is thrown during login 
- Throw unauthorized if a user token is null

Capture login exception

---

android/app/proguard-rules.pro
android/build.gradle

Might fix https://github.com/flutter/flutter/issues/58479
May fix startup error:
```
08-31 16:39:28.845 14123 14123 D AndroidRuntime: Shutting down VM
08-31 16:39:28.847 14123 14123 E AndroidRuntime: FATAL EXCEPTION: main
08-31 16:39:28.847 14123 14123 E AndroidRuntime: Process: com.junto.juntobetamobile, PID: 14123
08-31 16:39:28.847 14123 14123 E AndroidRuntime: java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver' appears in base.apk)
08-31 16:39:28.847 14123 14123 E AndroidRuntime: 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.registerWith(Unknown Source:0)
08-31 16:39:28.847 14123 …
```

Downgrade the gradle to 3.6.2

---

.gitignore
android/gradle/wrapper/gradle-wrapper.properties
ios/Flutter/.last_build_id
lib/app/material_app_with_theme.dart
lib/screens/collective/collective.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/welcome/widgets/sign_up_accept_button.dart
lib/widgets/end_drawer/end_drawer.dart

- Fixed sign out issue 🤞 
- Generate new gradle wrapper 
- Capture exception thrown by getRelationToGroup 
- Capture exception thrown when adding a member to the community center 
- Extract and breakup home page, reducing the number of times check server version is called

Various bugs and stabilization fixes

---

lib/app/app.dart
lib/backend/repositories/auth_repo.dart
lib/backend/repositories/user_repo.dart
lib/screens/welcome/bloc/auth_bloc.dart

- Adds a listener which logs the user out when the token is null

Log user out when token is null

---

lib/screens/welcome/bloc/auth_bloc.dart

This reverts commit 8efe3dfd88b72889a0b7a0bd7bfd9f715db0d593.
#	lib/screens/welcome/bloc/auth_bloc.dart

Revert "Log out user when 401 is thrown"

---

lib/app/community_center_addresses.dart
lib/backend/services/group_service.dart
lib/widgets/end_drawer/end_drawer.dart
lib/widgets/end_drawer/junto_center.dart

- Fix dev community center address
- Add people who aren't a part of the community center when opening screen

Community Center Fixes

---

lib/backend/backend.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/app_service.dart
lib/backend/services/collective_provider.dart
lib/backend/services/expression_service.dart
lib/backend/services/group_service.dart
lib/backend/services/notification_service.dart
lib/backend/services/search_service.dart
lib/backend/services/user_service.dart
lib/backend/user_data_provider.dart
lib/utils/junto_http.dart
pubspec.yaml

Reverts juntofoundation/junto-mobile#1068

Revert "Dio http replacement"

---

lib/utils/junto_http.dart

Reverts juntofoundation/junto-mobile#1070

Revert "Split token declaration"

---

lib/backend/backend.dart
lib/backend/repositories/user_repo.dart
lib/backend/services/app_service.dart
lib/backend/services/collective_provider.dart
lib/backend/services/expression_service.dart
lib/backend/services/group_service.dart
lib/backend/services/notification_service.dart
lib/backend/services/search_service.dart
lib/backend/services/user_service.dart
lib/backend/user_data_provider.dart
lib/utils/junto_http.dart
pubspec.yaml

Reverts juntofoundation/junto-mobile#1069

Revert "Revert "Dio http replacement""

---

.gitignore
lib/backend/backend.dart
lib/backend/services/app_service.dart
lib/backend/services/expression_service.dart
lib/backend/services/user_service.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/create/create_templates/link.dart
lib/screens/expression_open/expression_open.dart
lib/screens/notifications/notification_types/previews/photo_preview.dart
lib/utils/junto_http.dart
lib/widgets/dialogs/delete_account_dialog.dart
lib/widgets/end_drawer/junto_invite.dart
lib/widgets/end_drawer/junto_invite_dialog.dart
pubspec.lock
pubspec.yaml

To do:
Reimplment ss certificate for http implementation

Prepare release [WIP]

---

lib/screens/den/edit_den/edit_den.dart
lib/screens/den/edit_den/edit_den_text_field.dart
lib/widgets/member_widgets/bio.dart
lib/widgets/previews/comment_preview/previews/audio.dart
lib/widgets/previews/comment_preview/previews/photo.dart
lib/widgets/tab_bar/tab_bar.dart
lib/widgets/tab_bar/tab_bar_name.dart

Several UI Ops

---

lib/widgets/tab_bar/tab_bar.dart
pubspec.lock

Fix dark-light theme toggle in den tabbar

---

lib/screens/comment_open/comment_open.dart
lib/screens/expression_open/expression_open.dart
lib/screens/notifications/widgets/notification_tile.dart
lib/widgets/comments/bottom_comment_bar.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart

Improve replies

---

lib/screens/comment_open/comment_open_parent/comment_open_parent.dart
lib/screens/comment_open/comment_open_top.dart

Fix nav to den from comment open

---

lib/backend/services/expression_service.dart
lib/backend/services/notification_service.dart
lib/models/expression.dart
lib/models/junto_notification.dart
lib/models/junto_notification.g.dart
lib/models/user_model.g.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/create/create_templates/audio.dart
lib/screens/create/create_templates/link.dart
lib/screens/create/create_templates/longform.dart
lib/screens/create/create_templates/shortform.dart
lib/screens/expression_open/expressions/longform_open.dart
lib/screens/expression_open/expressions/shortform_open.dart
lib/screens/notifications/notification_types/mention_notification.dart
lib/screens/notifications/notification_types/previews/dynamic_preview.dart
lib/screens/notifications/notification_types/previews/link_preview.dart
lib/screens/notifications/notification_types/previews/shortform_preview.dart
lib/screens/notifications/notifications.dart
lib/screens/notifications/notifications_handler.dart
lib/screens/notifications/views/mentions_view.dart
lib/screens/notifications/views/relations_view.dart
lib/screens/notifications/widgets/notification_tile.dart
lib/widgets/comments/bottom_comment_bar.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/shortform.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/shortform.dart
pubspec.lock

- Fix notifs trigger
- Display mentions notifs
- Create separate mentions section in notifs
- Fix styling issues across app
**Pending**
Show user avatar/username in mention notifs

Finalize mentions 

---

lib/app/community_center_addresses.dart
lib/screens/welcome/welcome.dart

- Update error message
- Update dev cc feedback/updates addresses

Sign Up Improvements

---

lib/screens/notifications/notification_types/mention_notification.dart
lib/screens/notifications/widgets/notification_tile.dart

- Nav to expression from mention notif
- Show user avatar in mention notif

Improve mentions notifs

---

lib/screens/comment_open/types/shortform.dart
lib/screens/create/create_templates/shortform.dart
lib/screens/expression_open/expressions/shortform_open.dart
lib/widgets/previews/comment_preview/previews/shortform.dart
lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/shortform.dart
lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/shortform.dart

Fix mentions positioning in shortform
Remove underlines in shortform mentions

Pre-prod build clean up

---

lib/backend/backend.dart
lib/backend/services/expression_service.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/utils/bloc_delegate.dart
lib/utils/junto_http.dart

- Resolve bug with signed-in user thrown by Cognito

Resolve signed in cognito exception

---

lib/screens/create/create_actions/channel_search_modal.dart
lib/screens/create/create_actions/create_actions.dart
lib/screens/create/create_templates/audio.dart
lib/screens/create/create_templates/link.dart
lib/screens/create/create_templates/longform.dart
lib/screens/create/create_templates/photo.dart
lib/screens/create/create_templates/shortform.dart
lib/screens/create/create_templates/widgets/audio_review.dart
lib/screens/global_search/global_search.dart
lib/screens/global_search/search_bloc/search_bloc.dart
lib/screens/global_search/search_bloc/search_event.dart
lib/screens/global_search/search_bloc/search_state.dart
lib/utils/utils.dart
lib/widgets/comments/bottom_comment_bar.dart
lib/widgets/custom_parsed_text.dart
lib/widgets/mentions/channel_search_list.dart
pubspec.lock
pubspec.yaml

Channels support is completed just need to do some code cleanup & then it should be good to merge. @sunyatax can you take a look? also, I just copied the style for the mentions for the channels too, don't know if it needs to be styled differently or not, let me know I will update it by tommorrow.

Channels support

---

lib/app/community_center_addresses.dart

Recreate dev/staging community addressses

Update dev/staging community center addresses

---

lib/screens/expression_open/expression_open.dart
lib/widgets/previews/pack_preview/pack_preview.dart

- Fix opening expression in den
- Add pack indicator text to pack previews

Several pre-prod fixes

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/junto/juntobetamobile/MainActivity.java
android/app/src/main/kotlin/foundation/junto/junto_mobile/MainActivity.kt
lib/screens/create/create_templates/audio_service.dart
pubspec.lock
pubspec.yaml

@fayeed Running into a few issues with this implementation. See slack.
1) The playback time isn't correct or is inconsistent. In the video, it should be 9 seconds but it shows 12. Sometimes it shows 9.
2) When leaving and reopening the expression, it plays the volume but none of the playback row works anymore.
Going to revert this for now...

Revert "Audio playback android Fixed"

---

.gitignore
lib/app/material_app_with_theme.dart
lib/backend/repositories/auth_repo.dart
lib/screens/den/den.dart
lib/screens/notifications/views/all_view.dart
lib/screens/notifications/views/relations_view.dart
lib/screens/welcome/bloc/auth_bloc.dart
lib/screens/welcome/sign_in.dart
lib/widgets/bottom_nav.dart
lib/widgets/end_drawer/end_drawer.dart

- Revert back to previous logout method
- Fix pack requests in notifs
- Temp pause on push notifs

Pre-prod fixes

---

lib/screens/expression_open/expression_open.dart
lib/widgets/end_drawer/end_drawer.dart

- Fix log out navigation
- Fix navigation to reply to replies in notifications

Junto Alpha 0.2.4 (95)

---

lib/utils/junto_http.dart

Brotli compression header added

---

lib/screens/comment_open/comment_open.dart
lib/screens/expression_open/expression_open.dart
lib/widgets/action_items/comment_action_items.dart
lib/widgets/comments/comments_list.dart
lib/widgets/previews/comment_preview/comment_preview.dart

Multiple comments api call when going back fixed

---

lib/app/providers/bloc_providers.dart
lib/filters/bloc/channel_filtering_bloc.dart
lib/filters/bloc/channel_filtering_event.dart
lib/filters/bloc/channel_filtering_state.dart
lib/screens/den/den.dart
lib/screens/packs/packs.dart
lib/widgets/custom_parsed_text.dart
lib/widgets/drawer/filter_drawer_content.dart
lib/widgets/drawer/widgets/selected_channel.dart

Added multi channels filter support for perspective

---

android/app/proguard-rules.pro
ios/Podfile.lock
pubspec.lock
pubspec.yaml

After looking into the logs from Sentry & play console, I saw errors regarding the unmarshalling the error code returned by the AWS cognito plugin if the user is not signed in when they open the app, in dev mode, this doesn't crash but in prod it does, I found a possible solution that required some changes in proguard settings for android. 
https://stackoverflow.com/questions/44207343/android-and-aws-cognito-unable-to-unmarshall-error-response-with-proguard

Android auth fix

---

lib/screens/create/create_actions/widgets/create_app_bar.dart
lib/screens/create/create_actions/widgets/create_expression_scaffold.dart
lib/screens/create/create_review/audio_review.dart
lib/screens/create/create_templates/audio.dart
lib/screens/create/create_templates/link.dart
lib/screens/create/create_templates/longform.dart
lib/screens/create/create_templates/photo.dart
lib/screens/create/create_templates/shortform.dart
lib/screens/create/create_templates/widgets/audio_review.dart
lib/widgets/bottom_bar/junto_bottom_bar.dart

- Fix shortform hint text style
- Remove focus on text fields when going to next screen
- Maintain state of shortform and link in creation flow
- Increase size of bottom bar icons

Final changes pre 96

---

lib/screens/create/create_actions/widgets/choose_expression_sheet.dart
lib/screens/create/create_actions/widgets/create_expression_scaffold.dart
lib/screens/home/new_home.dart
lib/screens/notifications/notifications.dart
lib/screens/welcome/bloc/auth_bloc.dart
pubspec.lock
pubspec.yaml

- Temporarily hide notification settings (needs more testing + ui changes)
- Polish UX/UI of choose expression screen
- Add fade in to create expression screen

Junto Alpha 97 changes
